# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-10-18 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True, verbose_name=b'slug')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100, verbose_name=b'Solicitante')),
                ('slug', models.SlugField(unique=True, verbose_name=b'slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=b'Criado em')),
                ('departamento', models.ManyToManyField(blank=True, to='cantina.Departamento')),
            ],
            options={
                'verbose_name': 'Solicitacao',
                'verbose_name_plural': 'Solicitacoes',
            },
        ),
    ]
