# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-10-18 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cantina', '0002_auto_20161018_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='slug',
        ),
    ]
